name: pytests

on: 
  - pull_request
  - push
    
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install --upgrade pip
      - run: pip install pytest
      - run: pytest
      
      
